routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/administrador', function() {
  return view('admin.dashboard');
})->middleware('auth');

Route::group([
  'prefix' => 'admin',
  'middleware' => 'auth'],
function(){
  Route::get('profile', 'userManagerController@profile')->name('profile');
  Route::get('profile/edit', 'userManagerController@showEditProfile')->name('show.edit.profile.form');
  Route::put('profile/edit/{user}', 'userManagerController@editProfile')->name('edit.data.profile.form');
  Route::get('profile/edit/password', 'userManagerController@showEditPassword')->name('show.edit.profile.password.form');
  Route::put('profile/edit/password/{user}', 'userManagerController@editPassword')->name('edit.data.profile.password.form');
  Route::resource('users', 'UserController');
  Route::resource('cuadres', 'CuadreController');
  Route::resource('pagos', 'PagoController');
  Route::resource('datafonos', 'DatafonoController');
});

app/Cuadre.php
<?php

namespace App;

use Jenssegers\Date\Date;
use Illuminate\Database\Eloquent\Model;

class Cuadre extends Model
{
  protected $fillable = [
    'cuadre_venta',
    'cuadre_base',
    'cuadre_propina',
    'cuadre_descripcion'
  ];

  // Getters

  public function getCreatedAtAttribute($date)
  {
    return new Date($date);
  }

  // Setters



  // Relationships

  public function pagos()
  {
    return $this->hasMany(Pago::class);
  }

  public function datafonos()
  {
    return $this->hasMany(Datafono::class);
  }

  // Methods

  public function crearPagos($pagos)
  {
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }
  }

  public function crearDatafonos($datafonos)
  {
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function editarPagos($pagos)
  {
    $this->pagos()->delete();
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }

  }

  public function editarDatafonos($datafonos)
  {
    $this->datafonos()->delete();
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function totalBase()
  {
    $total = $this->cuadre_venta + $this->cuadre_base + $this->cuadre_propina;

    return $total;
  }

  public function sumaPagos()
  {
    $sumaPagos = 0;
    foreach ($this->pagos as $key => $pago) {
      $sumaPagos += $pago->pago_valor;
    }

    return $sumaPagos;
  }

  public function sumaDatafonos()
  {
    $sumaDatafonos = 0;
    foreach ($this->datafonos as $key => $datafono) {
      $sumaDatafonos += $datafono->datafono_valor;
    }

    return $sumaDatafonos;
  }

  public function totalSumaPD()
  {
    $totalSumaPD = $this->sumaPagos() + $this->sumaDatafonos();

    return $totalSumaPD;
  }

  public function totalFinal()
  {
    $totalFinal = $this->totalBase() - $this->totalSumaPD();

    return $totalFinal;
  }

}

app/Datafono.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Datafono extends Model
{
  protected $fillable = [
    'datafono_tipo',
    'datafono_valor',
    'datafono_desc',
    'cuadre_id'
  ];

  public function cuadre()
  {
    return $this->belongsTo(Cuadre::class);
  }
}

app/Http/Controllers/DatafonoController.php
<?php

namespace App\Http\Controllers;

use App\Datafono;
use App\Cuadre;
use App\Http\Requests\DatafonoRequest;
use App\Http\Requests\DatafonoUpdateRequest;
use Illuminate\Http\Request;

class DatafonoController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $datafonos = Datafono::all();
    return view('admin.Datafonos.index', compact('datafonos'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $cuadres = Cuadre::all();
    return view('admin.Datafonos.create', compact('cuadres'));
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(DatafonoRequest $request)
  {
    $datafonos = $request->datafonos;
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      $datafono->datafono_desc = $request->datafono_desc;
      $datafono->cuadre_id = $request->cuadre_id;
      $datafono->save();
    }
    return redirect()->route('datafonos.index')->with('info', 'Se han creado los datáfonos con éxito');
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Datafono  $datafono
  * @return \Illuminate\Http\Response
  */
  public function show(Datafono $datafono)
  {
    return view('admin.Datafonos.show', compact('datafono'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Datafono  $datafono
  * @return \Illuminate\Http\Response
  */
  public function edit(Datafono $datafono)
  {
    $cuadres = Cuadre::all();
    return view('admin.Datafonos.edit', compact('datafono', 'cuadres'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Datafono  $datafono
  * @return \Illuminate\Http\Response
  */
  public function update(DatafonoUpdateRequest $request, Datafono $datafono)
  {
    $datafono->update($request->all());
    return redirect()->route('datafonos.index')->with('info', 'Se ha actualizado el datáfono con éxito');
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Datafono  $datafono
  * @return \Illuminate\Http\Response
  */
  public function destroy(Datafono $datafono)
  {
    $datafono->delete();

    return back()->with('info', 'Se ha eliminado el datáfono con éxito');
  }
}

resources/views/admin/Datafonos/create.blade.php
@extends('admin.layout')

@section('styles')
  <!-- Select2 -->
  <link rel="stylesheet" href="/adminlte/bower_components/select2/dist/css/select2.min.css">
@stop

@section('header')
  <h1>
    Formulario de datáfonos
    <small>formulario donde se crean datáfonos</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('datafonos.index') }}"><i class="fa fa-credit-card"></i> Datáfonos</a></li>
    <li class="active">Crear datáfono</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Generar datáfonos</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')
      <form role="form" action="{{ route('datafonos.store') }}" method="post">
        @include('admin.Datafonos.partials.createForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')
  <!-- Select2 -->
  <script src="/adminlte/bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- CK Editor -->
  <script src="/adminlte/bower_components/ckeditor/ckeditor.js"></script>

  <!-- Page script -->
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2-cuadre').select2({
        language: "es",                
      })
      $('.select2-datafonos').select2({
        tags: true,
        language: "es"
      })
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('editor-datafono')
      //tooltips
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

@stop

resources/views/admin/Datafonos/edit.blade.php
@extends('admin.layout')

@section('styles')
  <!-- Select2 -->
  <link rel="stylesheet" href="/adminlte/bower_components/select2/dist/css/select2.min.css">
@stop

@section('header')
  <h1>
    Formulario de edición de datáfonos
    <small>formulario donde se editan datáfonos</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('datafonos.index') }}"><i class="fa fa-money"></i> Datáfono</a></li>
    <li class="active">Editar datáfono</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Editar datáfono</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')      
      <form role="form" action="{{ route('datafonos.update',$datafono) }}" method="post">
        @include('admin.Datafonos.partials.editForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')
  <!-- Select2 -->
  <script src="/adminlte/bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- CK Editor -->
  <script src="/adminlte/bower_components/ckeditor/ckeditor.js"></script>

  <!-- Page script -->
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2-cuadre').select2({
        language: "es"
      })
      $('.select2-datafono-tipo').select2({
        tags: true,
        language: "es",
        allowClear: true
      })
      $('.select2-datafono-valor').select2({
        tags: true,
        language: "es",
        allowClear: true
      })
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('editor-datafono')
      //tooltips
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

@stop

resources/views/admin/Datafonos/index.blade.php
@extends('admin.layout')

@section('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@stop

@section('header')
  <h1>
    Datáfonos
    <small>Lista de todos los datáfonos</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Datáfonos</li>
  </ol>
@stop

@section('content')
  <div class="box box-primary">
    <div class="box-header with-border">
      @include('admin.messages.info')
      <h3 class="box-title">Lista de datáfonos</h3>
      <a href="{{ route('datafonos.create') }}" class="btn btn-primary pull-right">Generar nuevo datáfono <i class="fa fa-plus"></i></a>
    </div>
    <div class="box-body">
      <table id="datafonos-table" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th width="20px">ID</th>
            <th>Tipo de datáfono</th>
            <th>Valor del datáfono</th>
            <th>descripción del datáfono</th>
            <th>Fecha del datáfono</th>
            <th>Cuadre al que pertenece</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          @foreach($datafonos as $datafono)
            <tr>
              <td>{{ $datafono->id }}</td>
              <td>{{ $datafono->datafono_tipo }}</td>
              <td>{{ $datafono->datafono_valor }}</td>
              @if(isset($datafono->datafono_desc))
                <td>{!! str_limit($datafono->datafono_desc, 30, '...') !!}</td>
              @else
                <td>No hay descripción</td>
              @endif
              <td>{{ $datafono->created_at }}</td>
              <td><a href="{{ route('cuadres.show', $datafono->cuadre->id) }}">{{ $datafono->cuadre->created_at->toFormattedDateString() }}</a></td>

              <td class="pull-right">
                <a class="btn btn-xs btn-info" href="{{ route('datafonos.show', $datafono) }}" ><i class="fa fa-eye"></i></a>
                <a class="btn btn-xs btn-warning" href="{{ route('datafonos.edit', $datafono) }}" ><i class="fa fa-pencil-square-o"></i></a>
                <a class="btn btn-xs btn-danger" href="#" data-toggle="modal" data-target="#deleteDatafono-{{ $datafono->id }}"><i class="fa fa-trash"></i></a>
    					</td>
            </tr>

            @include('admin.Datafonos.partials.deleteModal')

          @endforeach
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
@stop

@section('scripts')
  <!-- DataTables -->
  <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <!-- page script -->
  <script>
  $(function () {
    $('#datafonos-table').DataTable({
      'paging'      : true,
      'searching'   : true,
      'ordering'    : true,
      'autoWidth'   : false,
      "scrollX"     : true,
    })
  })
</script>
@stop

resources/views/admin/Datafonos/show.blade.php
@extends('admin.layout')

@section('styles')

@stop

@section('header')
  <h1>
    Detalle de datáfono
    <small>Detalle de un datáfono específico</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Datáfono - {{ $datafono->created_at->toFormattedDateString() }}</li>
  </ol>
@stop

@section('content')
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">Detalle del datáfono - {{ $datafono->created_at->toFormattedDateString() }}</h3><span> Cuadre al que pertenece - <a href="{{ route('cuadres.show', $datafono->cuadre->id) }}">{{ $datafono->cuadre->created_at->toFormattedDateString() }}</a></span>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
      <a style="margin-right: 10px"  href="{{ route('datafonos.edit', $datafono) }}" class="btn btn-primary pull-right"><i class="fa fa-pencil"></i> Editar datáfono</a>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-md-6">
          <h3>Tipo de datáfono:</h3>
          <div class="col-md-11 offset-1">
            <strong>{{ $datafono->datafono_tipo }}</strong>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Valor del datáfono:</h3>
          <div class="col-md-11 offset-1">
            <strong>{{ $datafono->datafono_valor }}</strong>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h3>Descripción del datáfono</h3>
          <br>
          {!! $datafono->datafono_desc or 'No hay descripción' !!}
        </div>
      </div>
    </div>
  </div>
@stop

@section('scripts')

@stop