routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/administrador', function() {
  return view('admin.dashboard');
})->middleware('auth');

Route::group([
  'prefix' => 'admin',
  'middleware' => 'auth'],
function(){
  Route::get('profile', 'userManagerController@profile')->name('profile');
  Route::get('profile/edit', 'userManagerController@showEditProfile')->name('show.edit.profile.form');
  Route::put('profile/edit/{user}', 'userManagerController@editProfile')->name('edit.data.profile.form');
  Route::get('profile/edit/password', 'userManagerController@showEditPassword')->name('show.edit.profile.password.form');
  Route::put('profile/edit/password/{user}', 'userManagerController@editPassword')->name('edit.data.profile.password.form');
  Route::resource('users', 'UserController');
  Route::resource('cuadres', 'CuadreController');
  Route::resource('pagos', 'PagoController');
  Route::resource('datafonos', 'DatafonoController');
});

app/Cuadre.php
<?php

namespace App;

use Jenssegers\Date\Date;
use Illuminate\Database\Eloquent\Model;

class Cuadre extends Model
{
  protected $fillable = [
    'cuadre_venta',
    'cuadre_base',
    'cuadre_propina',
    'cuadre_descripcion'
  ];

  // Getters

  public function getCreatedAtAttribute($date)
  {
    return new Date($date);
  }

  // Setters



  // Relationships

  public function pagos()
  {
    return $this->hasMany(Pago::class);
  }

  public function datafonos()
  {
    return $this->hasMany(Datafono::class);
  }

  // Methods

  public function crearPagos($pagos)
  {
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }
  }

  public function crearDatafonos($datafonos)
  {
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function editarPagos($pagos)
  {
    $this->pagos()->delete();
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }

  }

  public function editarDatafonos($datafonos)
  {
    $this->datafonos()->delete();
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function totalBase()
  {
    $total = $this->cuadre_venta + $this->cuadre_base + $this->cuadre_propina;

    return $total;
  }

  public function sumaPagos()
  {
    $sumaPagos = 0;
    foreach ($this->pagos as $key => $pago) {
      $sumaPagos += $pago->pago_valor;
    }

    return $sumaPagos;
  }

  public function sumaDatafonos()
  {
    $sumaDatafonos = 0;
    foreach ($this->datafonos as $key => $datafono) {
      $sumaDatafonos += $datafono->datafono_valor;
    }

    return $sumaDatafonos;
  }

  public function totalSumaPD()
  {
    $totalSumaPD = $this->sumaPagos() + $this->sumaDatafonos();

    return $totalSumaPD;
  }

  public function totalFinal()
  {
    $totalFinal = $this->totalBase() - $this->totalSumaPD();

    return $totalFinal;
  }

}

app/Pago.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pago extends Model
{
  protected $fillable = [
    'pago_nombre',
    'pago_valor',
    'pago_desc',
    'cuadre_id'
  ];

  public function cuadre()
  {
    return $this->belongsTo(Cuadre::class);
  }
}

app/Http/Controllers/PagoController.php
<?php

namespace App\Http\Controllers;

use App\Pago;
use App\Cuadre;
use App\Http\Requests\PagoRequest;
use App\Http\Requests\PagoUpdateRequest;
use Illuminate\Http\Request;

class PagoController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $pagos = Pago::all();
    return view('admin.Pagos.index', compact('pagos'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $cuadres = Cuadre::all();
    return view('admin.Pagos.create', compact('cuadres'));
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(PagoRequest $request)
  {
    $pagos = $request->pagos;
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      $pago->pago_desc = $request->pago_desc;
      $pago->cuadre_id = $request->cuadre_id;
      $pago->save();
    }
    return redirect()->route('pagos.index')->with('info', 'Se han creado los pagos con éxito');
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Pago  $pago
  * @return \Illuminate\Http\Response
  */
  public function show(Pago $pago)
  {
    return view('admin.Pagos.show', compact('pago'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Pago  $pago
  * @return \Illuminate\Http\Response
  */
  public function edit(Pago $pago)
  {
    $cuadres = Cuadre::all();
    return view('admin.Pagos.edit', compact('pago', 'cuadres'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Pago  $pago
  * @return \Illuminate\Http\Response
  */
  public function update(PagoUpdateRequest $request, Pago $pago)
  {
    $pago->update($request->all());
    return redirect()->route('pagos.index')->with('info', 'Se ha actualizado el pago con éxito');
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Pago  $pago
  * @return \Illuminate\Http\Response
  */
  public function destroy(Pago $pago)
  {
    $pago->delete();

    return back()->with('info', 'Se ha eliminado el pago con éxito');
  }
}

resources/views/admin/Pagos/create.blade.php
@extends('admin.layout')

@section('styles')
  <!-- Select2 -->
  <link rel="stylesheet" href="/adminlte/bower_components/select2/dist/css/select2.min.css">
@stop

@section('header')
  <h1>
    Formulario de pagos
    <small>formulario donde se crean pagos</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('pagos.index') }}"><i class="fa fa-money"></i> Pagos</a></li>
    <li class="active">Crear pago</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Generar pagos</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')      
      <form role="form" action="{{ route('pagos.store') }}" method="post">
        @include('admin.Pagos.partials.createForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')
  <!-- Select2 -->
  <script src="/adminlte/bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- CK Editor -->
  <script src="/adminlte/bower_components/ckeditor/ckeditor.js"></script>

  <!-- Page script -->
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2-cuadre').select2({
        language: "es"
      })
      $('.select2-pagos').select2({
        tags: true,
        language: "es"
      })
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('editor-pagos')
      //tooltips
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

@stop

resources/views/admin/Pagos/edit.blade.php
@extends('admin.layout')

@section('styles')
  <!-- Select2 -->
  <link rel="stylesheet" href="/adminlte/bower_components/select2/dist/css/select2.min.css">
@stop

@section('header')
  <h1>
    Formulario de edición de pagos
    <small>formulario donde se editan pagos</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('pagos.index') }}"><i class="fa fa-money"></i> Pagos</a></li>
    <li class="active">Editar pago</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Editar pagos</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')      
      <form role="form" action="{{ route('pagos.update',$pago) }}" method="post">
        @include('admin.Pagos.partials.editForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')
  <!-- Select2 -->
  <script src="/adminlte/bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- CK Editor -->
  <script src="/adminlte/bower_components/ckeditor/ckeditor.js"></script>

  <!-- Page script -->
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2-cuadre').select2({
        language: "es"
      })
      $('.select2-pago-nombre').select2({
        tags: true,
        language: "es",
        allowClear: true
      })
      $('.select2-pago-valor').select2({
        tags: true,
        language: "es",
        allowClear: true
      })
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('editor-pagos')
      //tooltips
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

@stop

resources/views/admin/Pagos/index.blade.php
@extends('admin.layout')

@section('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@stop

@section('header')
  <h1>
    Pagos
    <small>Lista de todos los pagos</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Pagos</li>
  </ol>
@stop

@section('content')
  <div class="box box-primary">
    <div class="box-header with-border">
      @include('admin.messages.info')
      <h3 class="box-title">Lista de pagos</h3>
      <a href="{{ route('pagos.create') }}" class="btn btn-primary pull-right">Generar nuevo pago <i class="fa fa-plus"></i></a>
    </div>
    <div class="box-body">
      <table id="pagos-table" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th with="20px">ID</th>
            <th>Nombre del pago</th>
            <th>Valor del pago</th>
            <th>Descripción del pago</th>
            <th>Fecha del pago</th>
            <th>Cuadre al que pertenece</th>
            <th>Accions</th>
          </tr>
        </thead>
        <tbody>
          @foreach($pagos as $pago)
            <tr>
              <td>{{ $pago->id }}</td>
              <td>{{ $pago->pago_nombre }}</td>
              <td>{{ $pago->pago_valor }}</td>
              @if(isset($pago->pago_desc))
                <td>{!! str_limit($pago->pago_desc, 30, '...') !!}</td>
              @else
                <td>No hay descripción</td>
              @endif
              <td>{{ $pago->created_at }}</td>
              <td><a href="{{ route('cuadres.show', $pago->cuadre->id) }}">{{ $pago->cuadre->created_at->toFormattedDateString() }}</a></td>

              <td class="pull-right">
                <a class="btn btn-xs btn-info" href="{{ route('pagos.show', $pago) }}" ><i class="fa fa-eye"></i></a>
                <a class="btn btn-xs btn-warning" href="{{ route('pagos.edit', $pago) }}" ><i class="fa fa-pencil-square-o"></i></a>
                <a class="btn btn-xs btn-danger" href="#" data-toggle="modal" data-target="#deletePago-{{ $pago->id }}"><i class="fa fa-trash"></i></a>
    					</td>

            </tr>

            @include('admin.Pagos.partials.deleteModal')

          @endforeach
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
@stop

@section('scripts')
  <!-- DataTables -->
  <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <!-- page script -->
  <script>
  $(function () {
    $('#pagos-table').DataTable({
      'paging'      : true,
      'searching'   : true,
      'ordering'    : true,
      'autoWidth'   : false,
      "scrollX"     : true,
    })
  })
</script>
@stop

resources/views/admin/Pagos/show.blade.php
@extends('admin.layout')

@section('styles')

@stop

@section('header')
  <h1>
    Detalle de pago
    <small>Detalle de un pago específico</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Pago - {{ $pago->created_at->toFormattedDateString() }}</li>
  </ol>
@stop

@section('content')
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">Detalle del pago - {{ $pago->created_at->toFormattedDateString() }}</h3><span> Cuadre al que pertenece - <a href="{{ route('cuadres.show', $pago->cuadre->id) }}">{{ $pago->cuadre->created_at->toFormattedDateString() }}</a></span>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
      <a style="margin-right: 10px"  href="{{ route('pagos.edit', $pago) }}" class="btn btn-primary pull-right"><i class="fa fa-pencil"></i> Editar pago</a>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-md-6">
          <h3>Nombre del pago:</h3>
          <div class="col-md-11 offset-1">
            <strong>{{ $pago->pago_nombre }}</strong>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Valor del pago:</h3>
          <div class="col-md-11 offset-1">
            <strong>{{ $pago->pago_valor }}</strong>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h3>Descripción del pago</h3>
          <br>
          {!! $pago->pago_desc or 'No hay descripción' !!}
        </div>
      </div>
    </div>
  </div>
@stop

@section('scripts')

@stop