routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/administrador', function() {
  return view('admin.dashboard');
})->middleware('auth');

Route::group([
  'prefix' => 'admin',
  'middleware' => 'auth'],
function(){
  Route::get('profile', 'userManagerController@profile')->name('profile');
  Route::get('profile/edit', 'userManagerController@showEditProfile')->name('show.edit.profile.form');
  Route::put('profile/edit/{user}', 'userManagerController@editProfile')->name('edit.data.profile.form');
  Route::get('profile/edit/password', 'userManagerController@showEditPassword')->name('show.edit.profile.password.form');
  Route::put('profile/edit/password/{user}', 'userManagerController@editPassword')->name('edit.data.profile.password.form');
  Route::resource('users', 'UserController');
  Route::resource('cuadres', 'CuadreController');
  Route::resource('pagos', 'PagoController');
  Route::resource('datafonos', 'DatafonoController');
});

app/Cuadre.php
<?php

namespace App;

use Jenssegers\Date\Date;
use Illuminate\Database\Eloquent\Model;

class Cuadre extends Model
{
  protected $fillable = [
    'cuadre_venta',
    'cuadre_base',
    'cuadre_propina',
    'cuadre_descripcion'
  ];

  // Getters

  public function getCreatedAtAttribute($date)
  {
    return new Date($date);
  }

  // Setters



  // Relationships

  public function pagos()
  {
    return $this->hasMany(Pago::class);
  }

  public function datafonos()
  {
    return $this->hasMany(Datafono::class);
  }

  // Methods

  public function crearPagos($pagos)
  {
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }
  }

  public function crearDatafonos($datafonos)
  {
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function editarPagos($pagos)
  {
    $this->pagos()->delete();
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }

  }

  public function editarDatafonos($datafonos)
  {
    $this->datafonos()->delete();
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function totalBase()
  {
    $total = $this->cuadre_venta + $this->cuadre_base + $this->cuadre_propina;

    return $total;
  }

  public function sumaPagos()
  {
    $sumaPagos = 0;
    foreach ($this->pagos as $key => $pago) {
      $sumaPagos += $pago->pago_valor;
    }

    return $sumaPagos;
  }

  public function sumaDatafonos()
  {
    $sumaDatafonos = 0;
    foreach ($this->datafonos as $key => $datafono) {
      $sumaDatafonos += $datafono->datafono_valor;
    }

    return $sumaDatafonos;
  }

  public function totalSumaPD()
  {
    $totalSumaPD = $this->sumaPagos() + $this->sumaDatafonos();

    return $totalSumaPD;
  }

  public function totalFinal()
  {
    $totalFinal = $this->totalBase() - $this->totalSumaPD();

    return $totalFinal;
  }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function setPasswordAttribute($password)
    {
      $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $users = User::all();
      return view('admin.Users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.Users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
      User::create($request->all());

      return redirect()->route('users.index')->with('info','Se ha creado el usuario con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
      return view('admin.Users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
      return view('admin.Users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
      $user->update($request->validated());
      return redirect()->route('users.index')->with('info', 'Se ha editado el usuario con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
      if($user->id === auth()->user()->id){
        return back()->with('error', 'No te puedes eliminar a ti mismo');
      }

      $user->delete();
      return back()->with('info', 'Se ha eliminado el usuario con éxito');
    }
}

resources/views/admin/Users/create.blade.php
@extends('admin.layout')

@section('styles')

@stop

@section('header')
  <h1>
    Formulario de usuario
    <small>formulario donde se crea el usuario</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('users.index') }}"><i class="fa fa-user"></i> Usuarios</a></li>
    <li class="active">Crear usuario</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Crear usuario</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')      
      <form role="form" action="{{ route('users.store') }}" method="post">
        @include('admin.Users.partials.createForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')

@stop

resources/views/admin/Users/edit.blade.php
@extends('admin.layout')

@section('styles')

@stop

@section('header')
  <h1>
    Formulario de edición de usuario
    <small>formulario donde se edita un usuario</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('users.index') }}"><i class="fa fa-user"></i> Usuarios</a></li>
    <li class="active">Editar usuario</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Editar usuario</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')      
      <form role="form" action="{{ route('users.update', $user) }}" method="post">
        @include('admin.Users.partials.editForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')

@stop

resources/views/admin/Users/index.blade.php
@extends('admin.layout')

@section('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@stop

@section('header')
  <h1>
    Usuarios
    <small>Lista de todos los usuarios</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Usuarios</li>
  </ol>
@stop

@section('content')
  <div class="box box-primary">
    <div class="box-header with-border">
      @include('admin.messages.info')
      @include('admin.messages.error')
      <h3 class="box-title">Lista de usuarios</h3>
      <a href="{{ route('users.create') }}" class="btn btn-primary pull-right">Crear nuevo Usuario <i class="fa fa-plus"></i></a>
    </div>
    <div class="box-body">
      <table id="cuadre-table" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th width="20px">ID</th>
            <th>Nombre</th>
            <th>Correo</th>
            <th>Miembro desde</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          @foreach($users as $user)
            <tr>
              <td>{{ $user->id }}</td>
              <td>{{ $user->name }}</td>
              <td>{{ $user->email }}</td>
              <td>{{ $user->created_at->toFormattedDateString() }}</td>

              <td class="pull-right">
                <a class="btn btn-xs btn-info" href="{{ route('users.show', $user) }}" ><i class="fa fa-eye"></i></a>
                <a class="btn btn-xs btn-warning" href="{{ route('users.edit', $user) }}" ><i class="fa fa-pencil-square-o"></i></a>
                <a class="btn btn-xs btn-danger" href="#" data-toggle="modal" data-target="#deleteUser-{{ $user->id }}"><i class="fa fa-trash"></i></a>
    					</td>
            </tr>

            @include('admin.Users.partials.deleteModal')

          @endforeach
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
@stop

@section('scripts')
  <!-- DataTables -->
  <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <!-- page script -->
  <script>
  $(function () {
    $('#cuadre-table').DataTable({
      'paging'      : true,
      'searching'   : true,
      'ordering'    : true,
      'autoWidth'   : false,
      "scrollX"     : true,
    })
  })
</script>
@stop

resources/views/admin/Users/show.blade.php
@extends('admin.layout')

@section('styles')

@stop

@section('header')
  <h1>
    Detalle de usuario
    <small>Detalle de un usuario específico</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Usuario - {{ $user->name }}</li>
  </ol>
@stop

@section('content')
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">Detalle del usuario - {{ $user->name }}</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
      <a style="margin-right: 10px"  href="{{ route('users.edit', $user) }}" class="btn btn-primary pull-right"><i class="fa fa-pencil"></i> Editar usuario</a>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-md-6">
          <h3>Email:</h3>
          <div class="col-md-11 offset-1">
            <strong>{{ $user->email }}</strong>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Miembro desde:</h3>
          <div class="col-md-11 offset-1">
            <strong>{{ $user->created_at->toFormattedDateString() }}</strong>
          </div>
        </div>
      </div>
    </div>
  </div>
@stop

@section('scripts')

@stop