routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/administrador', function() {
  return view('admin.dashboard');
})->middleware('auth');

Route::group([
  'prefix' => 'admin',
  'middleware' => 'auth'],
function(){
  Route::get('profile', 'userManagerController@profile')->name('profile');
  Route::get('profile/edit', 'userManagerController@showEditProfile')->name('show.edit.profile.form');
  Route::put('profile/edit/{user}', 'userManagerController@editProfile')->name('edit.data.profile.form');
  Route::get('profile/edit/password', 'userManagerController@showEditPassword')->name('show.edit.profile.password.form');
  Route::put('profile/edit/password/{user}', 'userManagerController@editPassword')->name('edit.data.profile.password.form');
  Route::resource('users', 'UserController');
  Route::resource('cuadres', 'CuadreController');
  Route::resource('pagos', 'PagoController');
  Route::resource('datafonos', 'DatafonoController');
});

app/Cuadre.php
<?php

namespace App;

use Jenssegers\Date\Date;
use Illuminate\Database\Eloquent\Model;

class Cuadre extends Model
{
  protected $fillable = [
    'cuadre_venta',
    'cuadre_base',
    'cuadre_propina',
    'cuadre_descripcion'
  ];

  // Getters

  public function getCreatedAtAttribute($date)
  {
    return new Date($date);
  }

  // Setters



  // Relationships

  public function pagos()
  {
    return $this->hasMany(Pago::class);
  }

  public function datafonos()
  {
    return $this->hasMany(Datafono::class);
  }

  // Methods

  public function crearPagos($pagos)
  {
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }
  }

  public function crearDatafonos($datafonos)
  {
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function editarPagos($pagos)
  {
    $this->pagos()->delete();
    for ($i=0; $i < count($pagos); $i++) {
      $pagosSeparados[] = explode('-',$pagos[$i]);
      $pago = new Pago;
      $pago->pago_nombre = $pagosSeparados[$i][0];
      $pago->pago_valor = $pagosSeparados[$i][1];
      if (count($pagosSeparados[$i]) > 2) {
        $pago->pago_desc = $pagosSeparados[$i][2];
      }
      $pago->cuadre_id = $this->id;
      $pago->save();
    }

  }

  public function editarDatafonos($datafonos)
  {
    $this->datafonos()->delete();
    for ($i=0; $i < count($datafonos); $i++) {
      $datafonosSeparados[] = explode('-',$datafonos[$i]);
      $datafono = new Datafono;
      $datafono->datafono_tipo = $datafonosSeparados[$i][0];
      $datafono->datafono_valor = $datafonosSeparados[$i][1];
      if (count($datafonosSeparados[$i]) > 2) {
        $datafono->datafono_desc = $datafonosSeparados[$i][2];
      }
      $datafono->cuadre_id = $this->id;
      $datafono->save();
    }
  }

  public function totalBase()
  {
    $total = $this->cuadre_venta + $this->cuadre_base + $this->cuadre_propina;

    return $total;
  }

  public function sumaPagos()
  {
    $sumaPagos = 0;
    foreach ($this->pagos as $key => $pago) {
      $sumaPagos += $pago->pago_valor;
    }

    return $sumaPagos;
  }

  public function sumaDatafonos()
  {
    $sumaDatafonos = 0;
    foreach ($this->datafonos as $key => $datafono) {
      $sumaDatafonos += $datafono->datafono_valor;
    }

    return $sumaDatafonos;
  }

  public function totalSumaPD()
  {
    $totalSumaPD = $this->sumaPagos() + $this->sumaDatafonos();

    return $totalSumaPD;
  }

  public function totalFinal()
  {
    $totalFinal = $this->totalBase() - $this->totalSumaPD();

    return $totalFinal;
  }

}

app/Http/Controllers/CuadreController.php
<?php

namespace App\Http\Controllers;

use App\Cuadre;
use App\Pago;
use App\Datafono;
use App\Http\Requests\CuadreRequest;
use Illuminate\Http\Request;

class CuadreController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $cuadres = Cuadre::all();
    return view('admin.Cuadres.index', compact('cuadres'));
  }

  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    return view('admin.Cuadres.create');
  }

  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(CuadreRequest $request)
  {
    $cuadre = Cuadre::create($request->all());

    $cuadre->crearPagos($request->pagos);
    $cuadre->crearDatafonos($request->datafonos);

    return redirect()->route('cuadres.index')->with('info', 'Se ha creado el cuadre con éxito');
  }

  /**
  * Display the specified resource.
  *
  * @param  \App\Cuadre  $cuadre
  * @return \Illuminate\Http\Response
  */
  public function show(Cuadre $cuadre)
  {
    return view('admin.Cuadres.show', compact('cuadre'));
  }

  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Cuadre  $cuadre
  * @return \Illuminate\Http\Response
  */
  public function edit(Cuadre $cuadre)
  {
    return view('admin.Cuadres.edit', compact('cuadre'));
  }

  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Cuadre  $cuadre
  * @return \Illuminate\Http\Response
  */
  public function update(CuadreRequest $request, Cuadre $cuadre)
  {
    $cuadre->update($request->all());

    $cuadre->editarPagos($request->pagos);
    $cuadre->editarDatafonos($request->datafonos);

    return redirect()->route('cuadres.index')->with('info', 'Se ha editado el cuadre con éxito');
  }

  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Cuadre  $cuadre
  * @return \Illuminate\Http\Response
  */
  public function destroy(Cuadre $cuadre)
  {
    $cuadre->pagos()->delete();
    $cuadre->datafonos()->delete();

    $cuadre->delete();

    return back()->with('info', 'Se ha eliminado el cuadre con éxito');
  }
}

resources/views/admin/Cuadres/create.blade.php
@extends('admin.layout')

@section('styles')
  <!-- Select2 -->
  <link rel="stylesheet" href="/adminlte/bower_components/select2/dist/css/select2.min.css">
@stop

@section('header')
  <h1>
    Formulario de cuadre
    <small>formulario donde se crea el cuadre</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('cuadres.index') }}"><i class="fa fa-usd"></i> Cuadres</a></li>
    <li class="active">Crear cuadre</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Generar cuadre</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')
      <form role="form" action="{{ route('cuadres.store') }}" method="post">
        @include('admin.Cuadres.partials.createForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')
  <!-- Select2 -->
  <script src="/adminlte/bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- CK Editor -->
  <script src="/adminlte/bower_components/ckeditor/ckeditor.js"></script>

  <!-- Page script -->
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2-pagos').select2({
        tags: true,
        language: "es",
      })
      $('.select2-datafonos').select2({
        tags: true,
        language: "es"
      })
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('editor-cuadres')
      //tooltips
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

@stop

resources/views/admin/Cuadres/edit.blade.php
@extends('admin.layout')

@section('styles')
  <!-- Select2 -->
  <link rel="stylesheet" href="/adminlte/bower_components/select2/dist/css/select2.min.css">
@stop

@section('header')
  <h1>
    Formulario de edición de cuadre
    <small>formulario donde se edita un cuadre</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ route('cuadres.index') }}"><i class="fa fa-usd"></i> Cuadres</a></li>
    <li class="active">Editar cuadre</li>
  </ol>
@stop

@section('content')
  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">Editar cuadre</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
    </div>
    <div class="box-body">
      @include('admin.messages.error')      
      <form role="form" action="{{ route('cuadres.update', $cuadre) }}" method="post">
        @include('admin.Cuadres.partials.editForm')
      </form>
    </div>
  </div>
@stop

@section('scripts')
  <!-- Select2 -->
  <script src="/adminlte/bower_components/select2/dist/js/select2.full.min.js"></script>
  <!-- CK Editor -->
  <script src="/adminlte/bower_components/ckeditor/ckeditor.js"></script>

  <!-- Page script -->
  <script>
    $(function () {
      //Initialize Select2 Elements
      $('.select2-pagos').select2({
        tags: true,
        language: "es"
      })
      $('.select2-datafonos').select2({
        tags: true,
        language: "es"
      })
      // Replace the <textarea id="editor1"> with a CKEditor
      // instance, using default configuration.
      CKEDITOR.replace('editor-cuadres')
      //tooltips
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

@stop

resources/views/admin/Cuadres/index.blade.php
@extends('admin.layout')

@section('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="/adminlte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@stop

@section('header')
  <h1>
    Cuadres Diarios
    <small>Resumen de todos los cuadres día por día</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Cuadres</li>
  </ol>
@stop

@section('content')
  <div class="box box-primary">
    <div class="box-header with-border">
      @include('admin.messages.info')
      <h3 class="box-title">Lista de cuadres</h3>
      <a href="{{ route('cuadres.create') }}" class="btn btn-primary pull-right">Generar nuevo cuadre <i class="fa fa-plus"></i></a>
    </div>
    <div class="box-body">
      <table id="cuadre-table" class="table table-bordered table-hover">
        <thead>
          <tr>
            <th width="20px">ID</th>
            <th>Fecha cuadre</th>
            <th>Venta</th>
            <th>Propinas</th>
            <th class="text-center">Acciones</th>
          </tr>
        </thead>
        <tbody>
          @foreach($cuadres as $cuadre)
            <tr>
              <td>{{ $cuadre->id }}</td>
              <td>{{ $cuadre->created_at->toFormattedDateString() }}</td>
              <td>{{ $cuadre->cuadre_venta }}</td>
              <td>{!! $cuadre->cuadre_propina !!}</td>

              <td class="pull-right">
                <a class="btn btn-xs btn-info" href="{{ route('cuadres.show', $cuadre) }}" ><i class="fa fa-eye"></i></a>
                <a class="btn btn-xs btn-warning" href="{{ route('cuadres.edit', $cuadre) }}" ><i class="fa fa-pencil-square-o"></i></a>
                <a class="btn btn-xs btn-danger" href="#" data-toggle="modal" data-target="#deleteCuadre-{{ $cuadre->id }}"><i class="fa fa-trash"></i></a>
    					</td>
            </tr>

            @include('admin.Cuadres.partials.deleteModal')

          @endforeach
        </tbody>
      </table>
    </div>
    <div class="box-footer">
      <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
@stop

@section('scripts')
  <!-- DataTables -->
  <script src="/adminlte/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/adminlte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

  <!-- page script -->
  <script>
  $(function () {
    $('#cuadre-table').DataTable({
      'paging'      : true,
      'searching'   : true,
      'ordering'    : true,
      'autoWidth'   : false,
      "scrollX"     : true,
    })
  })
</script>
@stop

resources/views/admin/Cuadres/show.blade.php
@extends('admin.layout')

@section('styles')

@stop

@section('header')
  <h1>
    Detalle de cuadre
    <small>Detalle de un cuandre específico</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('/administrador') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Cuadre - {{ $cuadre->created_at->toFormattedDateString() }}</li>
  </ol>
@stop

@section('content')
  <div class="box box-warning">
    <div class="box-header with-border">
      <h3 class="box-title">Detalle del cuadre - {{ $cuadre->created_at->toFormattedDateString() }}</h3>
      <a href="{{ URL::previous() }}" class="btn btn-info pull-right"><i class="fa fa-chevron-left"></i> Regresar</a>
      <a style="margin-right: 10px"  href="{{ route('cuadres.edit', $cuadre) }}" class="btn btn-primary pull-right"><i class="fa fa-pencil"></i> Editar cuadre</a>
    </div>
    <div class="box-body">
      <div class="row">
        <div class="col-md-6">
          <h3>Ventas:</h3>
          <div class="col-md-11 offset-1">
            <strong class="label label-primary">{{ number_format($cuadre->cuadre_venta,0,'','.') }} <i class="fa fa-dollar"></i></strong>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Base:</h3>
          <div class="col-md-11 offset-1">
            <strong class="label label-primary">{{ number_format($cuadre->cuadre_base,0,'','.') }} <i class="fa fa-dollar"></i></strong>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <h3>Propinas:</h3>
          <div class="col-md-11 offset-1">
            <strong class="label label-primary">{{ number_format($cuadre->cuadre_propina,0,'','.') }} <i class="fa fa-dollar"></i></strong>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-6">
          <h3>Pagos:</h3>
            @forelse($cuadre->pagos as $pago)
              <div class="col-md-11 offset-1">
                <span><strong>Pago nombre: </strong></span><span><a href="{{ route('pagos.show', $pago) }}">{{ $pago->pago_nombre }}</a></span><br>
                <span><strong>Pago valor: </strong></span><span class="label label-primary">{{ number_format($pago->pago_valor,0,'','.') }} <i class="fa fa-dollar"></i></span><br>
                  @if(isset($pago->pago_desc))
                    <span><strong>Pago descripción: </strong></span><span>{!! str_limit($pago->pago_desc, 50, '...') !!}</span>
                  @else
                    <span><strong>Pago descripción: </strong></span><span>No hay descripción</span>
                  @endif
                @unless($loop->last)
                  <hr>
                @endunless
              </div>
            @empty
              <div class="col-md-12 offset-1">
                <strong>No se registraron pagos para este cuadre. Si quieres registrar un nuevo pago has clic <a href="{{ route('pagos.create') }}">aquí</a> </strong>
              </div>
            @endforelse
            @if($cuadre->sumaPagos() > 0)
              <div class="col-md-10 offset-1">
                <h3>Total pagos: </h3><br>
                <strong class="alert alert-success">{{ number_format($cuadre->sumaPagos(),0,'','.') }} <i class="fa fa-dollar"></i></strong>
              </div>
            @endif
        </div>
        <div class="col-md-6">
          <h3>Datafonos:</h3>
            @forelse($cuadre->datafonos as $datafono)
              <div class="col-md-11 offset-1">
                <span><strong>Tipo de datáfono: </strong></span><span><a href="{{ route('datafonos.show', $datafono) }}">{{ $datafono->datafono_tipo }}</a></span><br>
                <span><strong>Datáfono valor: </strong></span><span class="label label-primary">{{ number_format($datafono->datafono_valor,0,'','.') }} <i class="fa fa-dollar"></i></span><br>
                  @if(isset($datafono->datafono_desc))
                    <span><strong>Datáfono descripción: </strong></span><span>{!! str_limit($datafono->datafono_desc, 50, '...') !!}</span>
                  @else
                    <span><strong>Datáfono descripción: </strong></span><span>No hay descripción</span>
                  @endif
                @unless($loop->last)
                  <hr>
                @endunless
              </div>
            @empty
              <div class="col-md-12 offset-1">
                <strong>No se registraron datáfonos para este cuadre. Si quieres registrar un nuevo datáfono has clic <a href="{{ route('datafonos.create') }}">aquí</a> </strong>
              </div>
            @endforelse
            @if($cuadre->sumaDatafonos() > 0)
              <div class="col-md-10 offset-1">
                <h3>Total datáfonos: </h3><br>
                <strong class="alert alert-success">{{ number_format($cuadre->sumaDatafonos(),0,'','.') }} <i class="fa fa-dollar"></i></strong>
              </div>
            @endif
        </div>
      </div>
      <br>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <h3>Descripción:</h3>
          {!! $cuadre->cuadre_descripcion or 'No hay descripción' !!}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-6">
          <h3>Total venta:</h3>
          <div class="col-md-11 offset-1">
            <h5 class="alert alert-success">{{ number_format($cuadre->totalBase(),0,'','.') }} <i class="fa fa-dollar"></i></h5>
          </div>
        </div>
        <div class="col-md-6">
          <h3>Salida caja y datáfono:</h3>
          <div class="col-md-11 offset-1">
            <h5 class="alert alert-success">{{ number_format($cuadre->totalSumaPD(),0,'','.') }} <i class="fa fa-dollar"></i></h5>
          </div>
        </div>
        <div class="col-md-12">
          <h3>Tener en efectivo:</h3>
          <div class="col-md-11 offset-1 alert alert-success">
            <h3>{{ number_format($cuadre->totalFinal(),0,'','.') }} <i class="fa fa-dollar"></i></h3>
          </div>
        </div>
      </div>

    </div>
  </div>
@stop

@section('scripts')

@stop